"""
AI Repository Report Generator
Generate comprehensive analysis reports in Markdown, PDF, and JSON formats.
"""

import os
import json
from datetime import datetime
from typing import Dict, Any, Optional


def generate_markdown_report(analysis_data: Dict[str, Any]) -> str:
    """Generate a full Markdown report from analysis data."""

    repo = analysis_data.get("repo", "Unknown Repository")
    health = analysis_data.get("health_score", "N/A")
    contributors = analysis_data.get("contributors", {})
    risky_files = analysis_data.get("risky_files", [])
    complex_functions = analysis_data.get("complex_functions", [])
    duplicates = analysis_data.get("duplicates", [])
    suggestions = analysis_data.get("suggestions", [])
    semantic_dupes = analysis_data.get("semantic_duplicates", [])
    risk_predictions = analysis_data.get("risk_predictions", [])
    large_modules = analysis_data.get("large_modules", [])
    code_churn = analysis_data.get("code_churn", [])

    md = []

    # Header
    md.append("# AI Repository Intelligence Report")
    md.append("")
    md.append(f"**Repository:** {repo}")
    md.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    md.append(f"**Health Score:** {health}/100")
    md.append("")
    md.append("---")
    md.append("")

    # Architecture Overview
    md.append("## Architecture Overview")
    md.append("")
    total_files = len(complex_functions) + len(large_modules)
    if total_files > 20:
        md.append("Layered service architecture detected with multiple modules.")
    elif total_files > 5:
        md.append("Moderate codebase with clear module separation.")
    else:
        md.append("Compact codebase with simple structure.")
    md.append("")

    # Health Score
    md.append("## Health Score")
    md.append("")
    if health != "N/A":
        if health >= 80:
            md.append(f"✅ **{health}/100** — Excellent health. Code quality is strong.")
        elif health >= 60:
            md.append(f"🟢 **{health}/100** — Good health. Minor improvements recommended.")
        elif health >= 40:
            md.append(f"⚠️ **{health}/100** — Fair health. Several areas need attention.")
        else:
            md.append(f"🔴 **{health}/100** — Critical. Significant refactoring required.")
    md.append("")

    # High Risk Files
    md.append("## High Risk Files")
    md.append("")
    if risk_predictions:
        for rf in risk_predictions[:10]:
            md.append(f"- **{rf['file']}** — Risk Score: {rf['risk_score']}")
    elif risky_files:
        for rf in risky_files[:10]:
            md.append(f"- **{rf['file']}** — Complexity: {rf.get('complexity', 'N/A')}")
    else:
        md.append("No high-risk files detected. ✅")
    md.append("")

    # Top Contributors
    md.append("## Top Contributors")
    md.append("")
    if contributors:
        sorted_contrib = sorted(contributors.items(), key=lambda x: x[1], reverse=True)
        for name, count in sorted_contrib[:10]:
            md.append(f"- **{name}** ({count} commits)")
    else:
        md.append("No contributor data available.")
    md.append("")

    # Complex Functions
    md.append("## Complex Functions")
    md.append("")
    if complex_functions:
        for cf in complex_functions[:15]:
            md.append(f"- `{cf['function']}` in `{cf['file']}` — Complexity: {cf['complexity']}")
    else:
        md.append("No overly complex functions detected. ✅")
    md.append("")

    # Semantic Duplicates
    md.append("## Semantic Duplicates")
    md.append("")
    if semantic_dupes:
        for sd in semantic_dupes[:10]:
            md.append(
                f"- `{sd['function1']}` ({sd['file1']}) ↔ "
                f"`{sd['function2']}` ({sd['file2']}) — "
                f"Similarity: {sd['similarity']}"
            )
    else:
        md.append("No semantic duplicates detected. ✅")
    md.append("")

    # Code Churn
    md.append("## Code Churn (Most Changed Files)")
    md.append("")
    if code_churn:
        for entry in code_churn[:10]:
            if isinstance(entry, (list, tuple)):
                md.append(f"- `{entry[0]}` — {entry[1]} changes")
            elif isinstance(entry, dict):
                md.append(f"- `{entry.get('file', '')}` — {entry.get('changes', 0)} changes")
    else:
        md.append("No churn data available.")
    md.append("")

    # Recommendations
    md.append("## Refactor Recommendations")
    md.append("")
    if suggestions:
        for s in suggestions:
            md.append(f"- {s}")
    else:
        md.append("No recommendations at this time.")
    md.append("")

    md.append("---")
    md.append("*Generated by AI Repository Intelligence Platform*")

    return "\n".join(md)


def generate_pdf_report(analysis_data: Dict[str, Any], output_dir: str = None) -> str:
    """
    Generate a PDF report using ReportLab.
    Returns the absolute file path to the generated PDF.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.units import inch
    except ImportError:
        return None

    # Use absolute path for output directory
    if output_dir is None:
        output_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "data")

    os.makedirs(output_dir, exist_ok=True)

    repo = analysis_data.get("repo", "unknown")
    repo_name = repo.rstrip("/").split("/")[-1] if "/" in repo else repo
    # Sanitize filename
    repo_name = "".join(c for c in repo_name if c.isalnum() or c in '-_.')
    filename = f"report_{repo_name}.pdf"
    filepath = os.path.join(output_dir, filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=22,
        textColor=HexColor("#6366f1"),
        spaceAfter=20
    )

    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=HexColor("#818cf8"),
        spaceBefore=16,
        spaceAfter=8
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=10,
        textColor=HexColor("#333333"),
        spaceAfter=4
    )

    def _esc(text):
        """Escape HTML special chars for ReportLab Paragraphs."""
        s = str(text)
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    # Title
    story.append(Paragraph("AI Repository Intelligence Report", title_style))
    story.append(Paragraph(f"Repository: {_esc(repo)}", body_style))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", body_style))

    health = analysis_data.get("health_score", "N/A")
    story.append(Paragraph(f"Health Score: {_esc(health)}/100", body_style))
    story.append(Spacer(1, 0.3 * inch))

    # High Risk Files
    risk_predictions = analysis_data.get("risk_predictions", [])
    if risk_predictions:
        story.append(Paragraph("High Risk Files", heading_style))
        for rf in risk_predictions[:10]:
            story.append(Paragraph(
                f"• {_esc(rf['file'])} — Risk Score: {rf['risk_score']}", body_style
            ))
        story.append(Spacer(1, 0.2 * inch))

    # Contributors
    contributors = analysis_data.get("contributors", {})
    if contributors:
        story.append(Paragraph("Top Contributors", heading_style))
        sorted_c = sorted(contributors.items(), key=lambda x: x[1], reverse=True)
        for name, count in sorted_c[:10]:
            story.append(Paragraph(f"• {_esc(name)} ({count} commits)", body_style))
        story.append(Spacer(1, 0.2 * inch))

    # Complex Functions
    complex_functions = analysis_data.get("complex_functions", [])
    if complex_functions:
        story.append(Paragraph("Complex Functions", heading_style))
        for cf in complex_functions[:10]:
            story.append(Paragraph(
                f"• {_esc(cf['function'])} in {_esc(cf['file'])} — Complexity: {cf['complexity']}",
                body_style
            ))
        story.append(Spacer(1, 0.2 * inch))

    # Recommendations
    suggestions = analysis_data.get("suggestions", [])
    if suggestions:
        story.append(Paragraph("Refactor Recommendations", heading_style))
        for s in suggestions:
            story.append(Paragraph(f"• {_esc(s)}", body_style))

    try:
        doc.build(story)
        return filepath
    except Exception as e:
        import traceback
        traceback.print_exc()
        return None


def generate_json_summary(analysis_data: Dict[str, Any]) -> Dict[str, Any]:
    """Generate a JSON summary of the analysis."""

    return {
        "repository": analysis_data.get("repo", "Unknown"),
        "generated_at": datetime.now().isoformat(),
        "health_score": analysis_data.get("health_score", None),
        "total_complex_functions": len(analysis_data.get("complex_functions", [])),
        "total_duplicates": len(analysis_data.get("duplicates", [])),
        "total_risky_files": len(analysis_data.get("risky_files", [])),
        "total_contributors": len(analysis_data.get("contributors", {})),
        "total_semantic_duplicates": len(analysis_data.get("semantic_duplicates", [])),
        "top_risk_files": analysis_data.get("risk_predictions", [])[:5],
        "top_contributors": dict(
            sorted(
                analysis_data.get("contributors", {}).items(),
                key=lambda x: x[1],
                reverse=True
            )[:5]
        ) if analysis_data.get("contributors") else {},
        "suggestions": analysis_data.get("suggestions", []),
    }
